url: "" # the base hostname and protocol to the site (without an ending /)
title: "UCSD Dragon Boat" 
description: >- # This means to ignore newlines until "future:"
  The Official Home Page of the UCSD Dragon Boat Team
future: false
published: true

# permalink: /:categories/:title # Removes default posts dates and hides file extension details


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/